=== uwlib-mig/schemasProject/xsd/properties_files.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    targetNamespace="https://uwlib-mig.github.io/schemasProject/xsd/"
    xmlns="https://uwlib-mig.github.io/schemasProject/xsd/"
    elementFormDefault="qualified">
    
    <xs:annotation>
        <xs:documentation>2024-04-14</xs:documentation>
        <xs:documentation>properties-files data structures defined here** are currently used in properties-files-to-HTML MAP workflow.</xs:documentation>
        <xs:documentation>**With exceptions such as element 'dspace', 'uwCustom', etc.</xs:documentation>
    </xs:annotation>
    
    <!-- update to include online schemas once stable, use
    https://uwlib-mig.github.io/schemasProject/xsd/genre_form.xsd
    https://uwlib-mig.github.io/schemasProject/xsd/collection.xsd -->
    <xs:include schemaLocation="coll_alias.xsd"/>
    <xs:include schemaLocation="genre_form.xsd"/>
    <xs:include schemaLocation="properties_extensions.xsd"/>
    
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
    <xs:import namespace="http://www.w3.org/2001/XMLSchema"
        schemaLocation="https://www.w3.org/2001/XMLSchema.xsd"/>

    <xs:element name="property" type="propertyType"/> 

    <xs:complexType name="propertyType">
        <xs:sequence>
            <xs:element name="uid">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="p[0-9]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="labels" type="labelType"/>
            <xs:element name="uwRequired" type="uwRequiredType"/>
            <xs:element name="cdm" type="cdmType"/>
            <xs:element name="dspace" type="dspaceType"/>
            <xs:element name="descriptions" type="descriptionsType"/>
            <xs:element name="examples" type="examplesType"/>
            <!-- for below types, see properties_extensions.xsd -->
            <xs:element name="additionalInfo" type="additionalInfoType"/>
            <xs:element name="marc" type="marcType"/>
            <xs:element name="xsd" type="xsdType"/>
            <xs:element name="rdf" type="rdfType"/>
            <xs:element name="history" type="historyType"/>            
        </xs:sequence>
        <xs:attribute ref="xml:base"/>
    </xs:complexType>

    <xs:complexType name="labelType">
        <xs:sequence>
            <xs:element name="platformIndependent" type="xs:string"/>
            <xs:element name="dc" type="dcterms"/>
            <xs:element name="dcNotEng" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="language"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="uwRequiredType">
        <xs:sequence>
            <xs:element name="uwStandalone" type="yesNo"/>
            <xs:element name="uwObject" type="yesNo"/>
            <xs:element name="uwItem" type="yesNo"/>
            <xs:element name="uwCustom" type="uwCustomRequiredType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="uwCustomRequiredType">
        <xs:simpleContent>
            <xs:extension base="yesNo">
                <xs:attribute name="co">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="no"/>
                            <xs:enumeration value="object"/>
                            <xs:enumeration value="item"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="dd" type="dd_type"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="dd_type">
        <xs:restriction>
            <xs:simpleType>
                <xs:list>
                    <xs:simpleType>
                        <xs:restriction base="xs:string"/>
                    </xs:simpleType>
                </xs:list>
            </xs:simpleType>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="cdmType">
        <xs:sequence>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="exportLabel" minOccurs="0" type="xs:string"/>
            <xs:element name="cdmDatatype" type="cdmDatatypeType"/>
            <xs:element name="cdmLarge" type="yesNo"/>
            <xs:element name="searchable" type="yesNo"/>
            <xs:element name="hidden" type="yesNo"/>
            <xs:element name="cdmRequired" type="yesNo"/>
            <xs:element name="cdmControlledVocab" type="yesNo"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="cdmDatatypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="fullText"/>
            <!-- following are not options for CONTENTdm 'Data type' field configuration -->
            <xs:enumeration value="cdmAdministrative"/>
            <xs:enumeration value="uwAdministrative"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="yesNo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
            <xs:enumeration value="notApplicable"/>
            <xs:enumeration value="ifApplicable"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="dspaceType">
        <xs:sequence>
            <xs:element name="dspaceProperty" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="descriptionsType">
        <xs:sequence>
            <xs:element name="definition" type="paraType" maxOccurs="unbounded"/>
            <xs:element name="instructions" type="default_para_type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="customization" type="custom_para_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="paraType">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="examplesType">
        <xs:sequence>
            <xs:element name="example" type="default_para_type" maxOccurs="unbounded"/>
            <xs:element name="customization" type="custom_para_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="dcterms">
        <xs:restriction base="xs:string">
            <xs:enumeration value="none"/>
            <xs:enumeration value="abstract"/>
            <xs:enumeration value="accessRights"/>
            <xs:enumeration value="accrualMethod"/>
            <xs:enumeration value="accrualPeriodicity"/>
            <xs:enumeration value="accrualPolicy"/>
            <xs:enumeration value="alternative"/>
            <xs:enumeration value="audience"/>
            <xs:enumeration value="available"/>
            <xs:enumeration value="bibliographicCitation"/>
            <xs:enumeration value="conformsTo"/>
            <xs:enumeration value="contributor"/>
            <xs:enumeration value="coverage"/>
            <xs:enumeration value="created"/>
            <xs:enumeration value="creator"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="dateAccepted"/>
            <xs:enumeration value="dateCopyrighted"/>
            <xs:enumeration value="dateSubmitted"/>
            <xs:enumeration value="description"/>
            <xs:enumeration value="educationLevel"/>
            <xs:enumeration value="extent"/>
            <xs:enumeration value="format"/>
            <xs:enumeration value="hasFormat"/>
            <xs:enumeration value="hasPart"/>
            <xs:enumeration value="hasVersion"/>
            <xs:enumeration value="identifier"/>
            <xs:enumeration value="instructionalMethod"/>
            <xs:enumeration value="isFormatOf"/>
            <xs:enumeration value="isPartOf"/>
            <xs:enumeration value="isReferencedBy"/>
            <xs:enumeration value="isReplacedBy"/>
            <xs:enumeration value="isRequiredBy"/>
            <xs:enumeration value="issued"/>
            <xs:enumeration value="isVersionOf"/>
            <xs:enumeration value="language"/>
            <xs:enumeration value="license"/>
            <xs:enumeration value="mediator"/>
            <xs:enumeration value="medium"/>
            <xs:enumeration value="modified"/>
            <xs:enumeration value="provenance"/>
            <xs:enumeration value="publisher"/>
            <xs:enumeration value="references"/>
            <xs:enumeration value="relation"/>
            <xs:enumeration value="replaces"/>
            <xs:enumeration value="requires"/>
            <xs:enumeration value="rights"/>
            <xs:enumeration value="rightsHolder"/>
            <xs:enumeration value="source"/>
            <xs:enumeration value="spatial"/>
            <xs:enumeration value="subject"/>
            <xs:enumeration value="tableOfContents"/>
            <xs:enumeration value="temporal"/>
            <xs:enumeration value="title"/>
            <xs:enumeration value="type"/>
            <xs:enumeration value="valid"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="default_para_type">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="co" type="cdm_object_type_type" use="required"/>
    </xs:complexType>

    <xs:complexType name="custom_para_type">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="dd" type="coll_alias_type"/>
        <xs:attribute name="co" type="cdm_object_type_type"/>
        <xs:attribute name="genre_form" type="genre_form_type"/>
    </xs:complexType>
    
    <xs:simpleType name="cdm_object_type_type">
        <xs:annotation>
            <xs:documentation>Use attributes of the type cdm_object_type_type to associate content with a particular kind of CONTENTdm object -- standalone item (sometimes also called standalone object), compound object, or compound-object item (that is, an item which is 'contained' in a compound object.</xs:documentation>
            <xs:documentation>Related: contentdm_maps/xsd/xml_map.xsd - map_structure_cdm_object_type_type</xs:documentation>
            <xs:documentation>Related: contentdm_maps/xsl/functions.xsl - xsl:function cdmm:convert_object_type_notation</xs:documentation>
        </xs:annotation>
        <xs:restriction>
            <xs:simpleType>
                <xs:list>
                    <xs:simpleType>
                        <xs:restriction base="xs:token">
                            <xs:enumeration value="all"/>
                            <xs:enumeration value="no">
                                <xs:annotation>
                                    <xs:documentation>Use this value to indicate that content describes practices for standalone items.</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="object">
                                <xs:annotation>
                                    <xs:documentation>Use this value to indicate that content describes practices for compound objects.</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="item">
                                <xs:annotation>
                                    <xs:documentation>Use this value to indicate that content describes practices for compound-object items.</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <!-- TO DO: eliminate use of 'agnostic', delete enumeration -->
                            <xs:enumeration value="agnostic">
                                <xs:annotation>
                                    <xs:documentation>Meaning/usage of 'agnostic' unclear.</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:list>
            </xs:simpleType>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== uwlib-mig/schemasProject/properties-files/digitalIdNumber.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="https://uwlib-mig.github.io/schemasProject/xsd/"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xsi:schemaLocation="https://uwlib-mig.github.io/schemasProject/xsd/
   https://uwlib-mig.github.io/schemasProject/xsd/properties_files.xsd">
   <uid>p30</uid>
   <labels>
      <platformIndependent>digitalIdNumber</platformIndependent>
      <dc>identifier</dc>
   </labels>
   <uwRequired>
      <uwStandalone>yes</uwStandalone>
      <uwObject>yes</uwObject>
      <uwItem>no</uwItem>
   </uwRequired>
   <cdm>
      <label>Digital ID Number</label>
      <cdmDatatype>text</cdmDatatype>
      <cdmLarge>no</cdmLarge>
      <searchable>yes</searchable>
      <hidden>no</hidden>
      <cdmRequired>no</cdmRequired>
      <cdmControlledVocab>no</cdmControlledVocab>
   </cdm>
   <dspace>
      <dspaceProperty/>
   </dspace>
   <descriptions>
      <definition>
         <para>Unique number assigned to each digital object in CONTENTdm for identification purposes.</para>
      </definition>
      <instructions co="no">
         <para>Enter the order number.</para>
         <para>Order number sequence must be obtained from appropriate staff.</para>
      </instructions>
      <instructions co="object">
         <para>Enter the order number.</para>
         <para>Order number sequence must be obtained from appropriate staff.</para>
      </instructions>
      <instructions co="item">
         <para>Enter the order number.</para>
         <para>Order number sequence must be obtained from appropriate staff.</para>
      </instructions>
      <customization co="object" dd="temp_alias_001" genre_form="default">
         <para>Do not enter values for Digital ID Number.</para>
         <para>Digital ID Numbers will be assigned by ITS-DS staff when resources and metadata are loaded to the collection.</para>
      </customization>
      <customization co="item" dd="temp_alias_001" genre_form="default">
         <para>Do not enter values for Digital ID Number.</para>
         <para>Digital ID Numbers will be assigned by ITS-DS staff when resources and metadata are loaded to the collection.</para>
      </customization>
      <customization co="no" dd="becker" genre_form="*">
         <para>Do not enter values for Digital ID Number.</para>
         <para>Digital ID Numbers will be assigned by ITS-DS staff when resources and metadata are loaded to the collection.</para>
      </customization>
   </descriptions>
   <examples>
      <example co="no">
         <para>CVW051</para>
         <para>COS321</para>
         <para>ARC0443</para>
      </example>
      <example co="object">
         <para>OHC0847</para>
      </example>
      <example co="item">
         <para>OHC0847-Audio</para>
         <para>OHC084-Transcript</para>
         <para>OHC084-Video</para>
      </example>
      <customization co="object" dd="uwtoh">
         <para>OWTOH201701</para>
         <para>OWTOH201702</para>
      </customization>
      <customization co="item" dd="uwtoh">
         <para>OWTOH201802-Audio</para>
         <para>UWTOH201802-Image</para>
         <para>UWTOH201802-Transcript</para>
      </customization>
      <customization co="object" dd="temp_alias_001" genre_form="default">
         <para>OHC0676</para>
         <para>OHC0010</para>
      </customization>
      <customization co="item" dd="temp_alias_001" genre_form="default">
         <para>OHC0676-Video</para>
         <para>OHC0676-Transcript</para>
         <para>OHC0010-Audio-01</para>
         <para>OHC0010-Audio-02</para>
         <para>OHC0010-Transcript</para>
      </customization>
   </examples>
   <additionalInfo>
      <admin co="no">
         <para>Photograph collections also have this property but it is labeled "Order Number."</para>
      </admin>
   </additionalInfo>
   <marc>
      <dcgMarcMapping/>
      <marcNotes>
         <para/>
      </marcNotes>
   </marc>
   <xsd>
      <typeInfo level="standalone object">
         <simpleType>
            <xs:restriction base="xs:string">
               <xs:minLength value="1"/>
            </xs:restriction>
         </simpleType>
      </typeInfo>
      <typeInfo level="item">
         <typeAttribute>xs:string</typeAttribute>
      </typeInfo>
   </xsd>
   <rdf> </rdf>
   <history>
      <dateCreated>
         <range>
            <start>2012-01-01</start>
            <end>2018-03-23</end>
         </range>
      </dateCreated>
      <created4Coll>Special Collections Oral Histories Collections</created4Coll>
      <justification>Special Collections wants a identifier for each object in CONTENTdm</justification>
      <changeLog>
         <change date="2022-07-27">Add custom guidance and examples for Tacoma Japanese Language School Project - temp_alias_001 - these may be broadly applicable, as present plan is for ITS-DS to assign these values, not collection managers</change>
      </changeLog>
   </history>
</property>

=== uwlib-mig/schemasProject/properties-files/organizationsDiscussed.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="https://uwlib-mig.github.io/schemasProject/xsd/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xsi:schemaLocation="https://uwlib-mig.github.io/schemasProject/xsd/
    https://uwlib-mig.github.io/schemasProject/xsd/properties_files.xsd">
    <uid>p137</uid>
    <labels>
        <platformIndependent>organizationsDiscussed</platformIndependent>
        <!-- 2022-09-20 'none' to 'subject' per MIG 2022-09-14 -->
        <dc>subject</dc>
    </labels>
    <uwRequired>
        <uwStandalone>no</uwStandalone>
        <uwObject>no</uwObject>
        <uwItem>no</uwItem>
    </uwRequired>
    <cdm>
        <label>Organizations Discussed</label>
        <cdmDatatype>text</cdmDatatype>
        <cdmLarge>no</cdmLarge>
        <searchable>yes</searchable>
        <hidden>no</hidden>
        <cdmRequired>no</cdmRequired>
        <cdmControlledVocab>yes</cdmControlledVocab>
    </cdm>
    <dspace>
        <dspaceProperty></dspaceProperty>
    </dspace>
    <descriptions>
        <definition>
            <para>Organizations given significant attention in the resource.</para>
        </definition>
        <!-- DRAFT, extremely brief default instructions -->
        <instructions co="object">
            <para>Provide the name or names of an organization or organizations given significant attention in the resource.</para>
            <para>If possible, use a controlled form for each organization's name.</para>
        </instructions>
        <instructions co="no">
            <para>Provide the name or names of an organization or organizations given significant attention in the resource.</para>
            <para>If possible, use a controlled form for each organization's name.</para>
        </instructions>
        <customization co="object" dd="p16786coll3" genre_form="Oral_histories">
            <para>Provide the name or names of an organization or organizations given significant attention in the interview.</para>
            <para>When appropriate, search the &lt;a href="https://id.loc.gov/authorities/names.html"&gt;Library of Congress Name Authority File&lt;/a&gt; via id.loc.gov for the names of organizations discussed in the oral history.</para>
            <para>If a potential match is found, confirm that it is the organization associated with the resource: it may be helpful to review information included in the web display such as source(s) of information, and/or to follow the links provided for exact and/or closely matching concepts from other schemes.</para>
            <para>Copy the name string for use just as it appears at the top of the page, above the URI(s), including dates.</para>
            <para>If no match is found, record an organization name.</para>
            <para>When recording names without a match in the NAF, reuse the recorded form consistently when the same person appears in the metadata for a different resource.</para>
            <para>Separate multiple entries with a semicolon and space (“; “).</para>
            <para>Order of values does not matter.</para>
        </customization>
        <customization co="no" dd="p16786coll3">
            <para>Provide the name or names of an organization or organizations given significant attention in the interview.</para>
            <para>When appropriate, search the &lt;a href="https://id.loc.gov/authorities/names.html"&gt;Library of Congress Name Authority File&lt;/a&gt; via id.loc.gov for the names of organizations discussed in the oral history.</para>
            <para>If a potential match is found, confirm that it is the organization associated with the resource: it may be helpful to review information included in the web display such as source(s) of information, and/or to follow the links provided for exact and/or closely matching concepts from other schemes.</para>
            <para>Copy the name string for use just as it appears at the top of the page, above the URI(s), including dates.</para>
            <para>If no match is found, record an organization name.</para>
            <para>When recording names without a match in the NAF, reuse the recorded form consistently when the same person appears in the metadata for a different resource.</para>
            <para>Separate multiple entries with a semicolon and space (“; “).</para>
            <para>Order of values does not matter.</para>
        </customization>
        <customization co="object" dd="temp_alias_001" genre_form="default">
            <para>Enter the name(s) of organizations mentioned.</para>
            <para>&lt;br/&gt;</para>
            <para>When appropriate, search the &lt;a href="https://id.loc.gov/authorities/names.html"&gt;Library of Congress Name Authority File via id.loc.gov&lt;/a&gt; for the organization.</para>
            <para>If a potential match is found, confirm that it is the organization associated with the resource. It may be helpful to review information included in the web display such as source(s) of information, and/or to follow the links provided for exact and/or closely matching concepts from other schemes.</para>
            <para>Copy the form of name as it appears at the top of the page, including dates.</para>
            <para>You may provide the value 'xyz' for the Cataloging property to indicate to cataloging staff that review of controlled forms of names is requested.</para>
            <para>&lt;br/&gt;</para>
            <para>If no record exists, enter the name(s) used by interviewees.</para>
            <para>Separate multiple values with a semicolon.</para>
        </customization>
        <customization co="no" dd="becker" genre_form="*">
            <para>&#x1F4DA; For review/input by cataloging staff</para>
            <para>&lt;br/&gt;Use the form of corporate name from the Library of Congress Name Authority File, if available.</para>
            <para>Separate multiple entries with a semicolon and space (“; “).</para>
        </customization>
    </descriptions>
    <examples>
        <!-- DRAFT defaults for object, standalone -->
        <example co="object">
            <para>Schipperke Club of America</para>
            <para>International Longshoremen's Association. Local 38-97 (Tacoma, Wash.)</para>
            <para>United States. Central Intelligence Agency. Conflict Issues Division</para>
        </example>
        <!-- should really be using co="all" but my styesheet doesn't account for "all" or "agnostic" -->
        <example co="no">
            <para>Schipperke Club of America</para>
            <para>International Longshoremen's Association. Local 38-97 (Tacoma, Wash.)</para>
            <para>United States. Central Intelligence Agency. Conflict Issues Division</para>
        </example>
        <customization co="object" dd="p16786coll3" genre_form="Oral_histories">
            <para>Congregation Ezra Bessaroth</para>
            <para>Congregation Ezra Bessaroth; Longacres Race Track</para>
        </customization>
        <customization co="object" dd="temp_alias_001" genre_form="default">
            <para>Tacoma Lumber Company; Superior Hotel; Stadium High School</para>
            <para>Methodist Church; Buddhist Church; Baptist Church</para>
            <para>Lincoln High School (Tacoma, Wash.)</para>
            <para>Japanese American Citizens' League</para>
            <para>Fort Lewis (Wash.)</para>
            <para>Airway Market</para>
        </customization>
    </examples>
    <additionalInfo></additionalInfo>
    <marc>
        <dcgMarcMapping></dcgMarcMapping>
    </marc>
    <xsd></xsd>
    <rdf></rdf>
    <history>
        <dateCreated>
            <range>
                <start>2021-10-03</start>
                <end>2021-10-26</end>
            </range>
        </dateCreated>
        <created4Coll>Sephardic Studies Digital Collection - p16786coll3</created4Coll>
        <justification>"Organizations Discussed" property exists in &lt;a href="https://www.lib.washington.edu/cams/mig/datadicts/special-collections-oral-histories-data-dictionary"&gt;Special Collections Oral Histories Data Dictionary&lt;/a&gt;, defining (with some changes and added specificity) for continued use and output to HTML MAPs.</justification>
        <changeLog>
            <change></change>
        </changeLog>
    </history>
</property>
