=== uwlib-mig/schemasProject/xsd/properties_files.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    targetNamespace="https://uwlib-mig.github.io/schemasProject/xsd/"
    xmlns="https://uwlib-mig.github.io/schemasProject/xsd/"
    elementFormDefault="qualified">
    
    <xs:annotation>
        <xs:documentation>2024-04-14</xs:documentation>
        <xs:documentation>properties-files data structures defined here** are currently used in properties-files-to-HTML MAP workflow.</xs:documentation>
        <xs:documentation>**With exceptions such as element 'dspace', 'uwCustom', etc.</xs:documentation>
    </xs:annotation>
    
    <!-- update to include online schemas once stable, use
    https://uwlib-mig.github.io/schemasProject/xsd/genre_form.xsd
    https://uwlib-mig.github.io/schemasProject/xsd/collection.xsd -->
    <xs:include schemaLocation="coll_alias.xsd"/>
    <xs:include schemaLocation="genre_form.xsd"/>
    <xs:include schemaLocation="properties_extensions.xsd"/>
    
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
    <xs:import namespace="http://www.w3.org/2001/XMLSchema"
        schemaLocation="https://www.w3.org/2001/XMLSchema.xsd"/>

    <xs:element name="property" type="propertyType"/> 

    <xs:complexType name="propertyType">
        <xs:sequence>
            <xs:element name="uid">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="p[0-9]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="labels" type="labelType"/>
            <xs:element name="uwRequired" type="uwRequiredType"/>
            <xs:element name="cdm" type="cdmType"/>
            <xs:element name="dspace" type="dspaceType"/>
            <xs:element name="descriptions" type="descriptionsType"/>
            <xs:element name="examples" type="examplesType"/>
            <!-- for below types, see properties_extensions.xsd -->
            <xs:element name="additionalInfo" type="additionalInfoType"/>
            <xs:element name="marc" type="marcType"/>
            <xs:element name="xsd" type="xsdType"/>
            <xs:element name="rdf" type="rdfType"/>
            <xs:element name="history" type="historyType"/>            
        </xs:sequence>
        <xs:attribute ref="xml:base"/>
    </xs:complexType>

    <xs:complexType name="labelType">
        <xs:sequence>
            <xs:element name="platformIndependent" type="xs:string"/>
            <xs:element name="dc" type="dcterms"/>
            <xs:element name="dcNotEng" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="language"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="uwRequiredType">
        <xs:sequence>
            <xs:element name="uwStandalone" type="yesNo"/>
            <xs:element name="uwObject" type="yesNo"/>
            <xs:element name="uwItem" type="yesNo"/>
            <xs:element name="uwCustom" type="uwCustomRequiredType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="uwCustomRequiredType">
        <xs:simpleContent>
            <xs:extension base="yesNo">
                <xs:attribute name="co">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="no"/>
                            <xs:enumeration value="object"/>
                            <xs:enumeration value="item"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="dd" type="dd_type"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="dd_type">
        <xs:restriction>
            <xs:simpleType>
                <xs:list>
                    <xs:simpleType>
                        <xs:restriction base="xs:string"/>
                    </xs:simpleType>
                </xs:list>
            </xs:simpleType>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="cdmType">
        <xs:sequence>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="exportLabel" minOccurs="0" type="xs:string"/>
            <xs:element name="cdmDatatype" type="cdmDatatypeType"/>
            <xs:element name="cdmLarge" type="yesNo"/>
            <xs:element name="searchable" type="yesNo"/>
            <xs:element name="hidden" type="yesNo"/>
            <xs:element name="cdmRequired" type="yesNo"/>
            <xs:element name="cdmControlledVocab" type="yesNo"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="cdmDatatypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="fullText"/>
            <!-- following are not options for CONTENTdm 'Data type' field configuration -->
            <xs:enumeration value="cdmAdministrative"/>
            <xs:enumeration value="uwAdministrative"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="yesNo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
            <xs:enumeration value="notApplicable"/>
            <xs:enumeration value="ifApplicable"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="dspaceType">
        <xs:sequence>
            <xs:element name="dspaceProperty" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="descriptionsType">
        <xs:sequence>
            <xs:element name="definition" type="paraType" maxOccurs="unbounded"/>
            <xs:element name="instructions" type="default_para_type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="customization" type="custom_para_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="paraType">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="examplesType">
        <xs:sequence>
            <xs:element name="example" type="default_para_type" maxOccurs="unbounded"/>
            <xs:element name="customization" type="custom_para_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="dcterms">
        <xs:restriction base="xs:string">
            <xs:enumeration value="none"/>
            <xs:enumeration value="abstract"/>
            <xs:enumeration value="accessRights"/>
            <xs:enumeration value="accrualMethod"/>
            <xs:enumeration value="accrualPeriodicity"/>
            <xs:enumeration value="accrualPolicy"/>
            <xs:enumeration value="alternative"/>
            <xs:enumeration value="audience"/>
            <xs:enumeration value="available"/>
            <xs:enumeration value="bibliographicCitation"/>
            <xs:enumeration value="conformsTo"/>
            <xs:enumeration value="contributor"/>
            <xs:enumeration value="coverage"/>
            <xs:enumeration value="created"/>
            <xs:enumeration value="creator"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="dateAccepted"/>
            <xs:enumeration value="dateCopyrighted"/>
            <xs:enumeration value="dateSubmitted"/>
            <xs:enumeration value="description"/>
            <xs:enumeration value="educationLevel"/>
            <xs:enumeration value="extent"/>
            <xs:enumeration value="format"/>
            <xs:enumeration value="hasFormat"/>
            <xs:enumeration value="hasPart"/>
            <xs:enumeration value="hasVersion"/>
            <xs:enumeration value="identifier"/>
            <xs:enumeration value="instructionalMethod"/>
            <xs:enumeration value="isFormatOf"/>
            <xs:enumeration value="isPartOf"/>
            <xs:enumeration value="isReferencedBy"/>
            <xs:enumeration value="isReplacedBy"/>
            <xs:enumeration value="isRequiredBy"/>
            <xs:enumeration value="issued"/>
            <xs:enumeration value="isVersionOf"/>
            <xs:enumeration value="language"/>
            <xs:enumeration value="license"/>
            <xs:enumeration value="mediator"/>
            <xs:enumeration value="medium"/>
            <xs:enumeration value="modified"/>
            <xs:enumeration value="provenance"/>
            <xs:enumeration value="publisher"/>
            <xs:enumeration value="references"/>
            <xs:enumeration value="relation"/>
            <xs:enumeration value="replaces"/>
            <xs:enumeration value="requires"/>
            <xs:enumeration value="rights"/>
            <xs:enumeration value="rightsHolder"/>
            <xs:enumeration value="source"/>
            <xs:enumeration value="spatial"/>
            <xs:enumeration value="subject"/>
            <xs:enumeration value="tableOfContents"/>
            <xs:enumeration value="temporal"/>
            <xs:enumeration value="title"/>
            <xs:enumeration value="type"/>
            <xs:enumeration value="valid"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="default_para_type">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="co" type="cdm_object_type_type" use="required"/>
    </xs:complexType>

    <xs:complexType name="custom_para_type">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="dd" type="coll_alias_type"/>
        <xs:attribute name="co" type="cdm_object_type_type"/>
        <xs:attribute name="genre_form" type="genre_form_type"/>
    </xs:complexType>
    
    <xs:simpleType name="cdm_object_type_type">
        <xs:annotation>
            <xs:documentation>Use attributes of the type cdm_object_type_type to associate content with a particular kind of CONTENTdm object -- standalone item (sometimes also called standalone object), compound object, or compound-object item (that is, an item which is 'contained' in a compound object.</xs:documentation>
            <xs:documentation>Related: contentdm_maps/xsd/xml_map.xsd - map_structure_cdm_object_type_type</xs:documentation>
            <xs:documentation>Related: contentdm_maps/xsl/functions.xsl - xsl:function cdmm:convert_object_type_notation</xs:documentation>
        </xs:annotation>
        <xs:restriction>
            <xs:simpleType>
                <xs:list>
                    <xs:simpleType>
                        <xs:restriction base="xs:token">
                            <xs:enumeration value="all"/>
                            <xs:enumeration value="no">
                                <xs:annotation>
                                    <xs:documentation>Use this value to indicate that content describes practices for standalone items.</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="object">
                                <xs:annotation>
                                    <xs:documentation>Use this value to indicate that content describes practices for compound objects.</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="item">
                                <xs:annotation>
                                    <xs:documentation>Use this value to indicate that content describes practices for compound-object items.</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <!-- TO DO: eliminate use of 'agnostic', delete enumeration -->
                            <xs:enumeration value="agnostic">
                                <xs:annotation>
                                    <xs:documentation>Meaning/usage of 'agnostic' unclear.</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:list>
            </xs:simpleType>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== uwlib-mig/schemasProject/properties-files/intervieweeBiography.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="https://uwlib-mig.github.io/schemasProject/xsd/"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xsi:schemaLocation="https://uwlib-mig.github.io/schemasProject/xsd/
   https://uwlib-mig.github.io/schemasProject/xsd/properties_files.xsd">
   <uid>p46</uid>
   <labels>
      <platformIndependent>intervieweeBiography</platformIndependent>
      <dc>description</dc>
   </labels>
   <uwRequired>
      <uwStandalone>no</uwStandalone>
      <uwObject>no</uwObject>
      <uwItem>no</uwItem>
   </uwRequired>
   <cdm>
      <label>Interviewee Biography</label>
      <cdmDatatype>text</cdmDatatype>
      <cdmLarge>no</cdmLarge>
      <searchable>no</searchable>
      <hidden>no</hidden>
      <cdmRequired>no</cdmRequired>
      <cdmControlledVocab>no</cdmControlledVocab>
   </cdm>
   <dspace>
      <dspaceProperty/>
   </dspace>
   <descriptions>
      <definition>
         <para>Biographical information about a person interviewed.</para>
      </definition>
      <instructions co="object">
         <!-- these don't seem like default instructions, they seem like project-specific instructions; ah, I see admin note below -->
         <para>Enter a brief biography of the interviewee that notes their scholarly or professional background and significant contributions to UW Tacoma.</para>
         <para>Highlight self-identified characteristics mentioned during the interview that contributed to interviewee’s perspective.</para>
      </instructions>
      <customization co="object" dd="p16786coll3" resourceType="oh">
         <para>Enter brief biographical information about the interviewee.</para>
         <para>Provide primarily biographical information as mentioned in the interview and/or related to topics discussed in the interview.</para>
      </customization>
      <customization co="no" dd="p16786coll3">
         <para>Enter brief biographical information about the interviewee.</para>
         <para>Provide primarily biographical information as mentioned in the interview and/or related to topics discussed in the interview.</para>
      </customization>
   </descriptions>
   <examples>
      <example co="object">
         <para>Michael Honey was born in 1947 in Lansing, Michigan. He grew up in Williamston, Pontiac, and Grand Rapids in Michigan, and Toledo, Ohio. His father was a World War II veteran and urban planner–turned professor who was born into an English farming family in Michigan. His mother came from a French-Canadian working-class family in Detroit. This background had a profound influence on Dr. Honey’s views, his affinity for union workers, and his later academic interests. Honey attended Oakland University, then an experimental, humanities-centered college in southeast Michigan, from 1965 to 1969. Amid the escalation of the Vietnam War, he received approval for his conscientious objector status when he graduated.</para>
         <para>After college, he went to Kentucky and subsequently spent six years in Memphis to serve as the Southern Director of the National Committee Against Repressive Legislation. He completed his graduate degrees at Howard University in Washington, D.C., and at Northern Illinois University, where he focused his research on labor history and developed his first book, Southern Labor and Black Civil Rights. He has since authored several other books, including Going Down Jericho Road: The Memphis Strike, Martin Luther King's Last Campaign.</para>
         <para>He came to University of Washington Tacoma in 1990 as a founding faculty member. Currently holding the Fred and Dorothy Haley endowed professorship of Humanities, he teaches African-American and labor history. During his time at UW Tacoma, he has also served as the Harry Bridges Endowed Chair of Labor Studies.</para>
      </example>
      <customization co="object" dd="p16786coll3" resourceType="oh">
         <para>Lela Abravanel was born in Salonica [Thessaloniki] Greece. She discusses her childhood in Las Kampanyas, a suburb of Salonica, and how she spoke French with her parents.</para>
      </customization>
      <customization co="no" dd="p16786coll3">
         <para>Lela Abravanel was born in Salonica [Thessaloniki] Greece. She discusses her childhood in Las Kampanyas, a suburb of Salonica, and how she spoke French with her parents.</para>
      </customization>
   </examples>
   <additionalInfo>
      <admin co="object">
         <para>To re-use this property, existing property properties should be reorganized as customizations for UWT-OH, then general properties of this property can be made more universal.</para>
      </admin>
   </additionalInfo>
   <marc>
      <dcgMarcMapping/>
      <marcNotes/>
   </marc>
   <xsd>
      <typeInfo level="object">
         <typeAttribute>xs:string</typeAttribute>
      </typeInfo>
   </xsd>
   <rdf/>
   <history>
      <dateCreated>
         <single>2018-03-23</single>
      </dateCreated>
      <created4Coll>University of Washington Tacoma Oral Histories</created4Coll>
      <justification>The UWT Oral Histories wanted to display biographical information about interviewees.</justification>
      <changeLog>
         <change date="2021-09-23">Change label for display in CONTENTdm UI to "Interviewee Biography" (from simply "Biography") in the interest of 1) aligning more closely with property definition 2) reducing confusion, given the existence of biography.xml with UI label "Biography", 3) normalizing prooperty labels overall. See also biography.xml, intervieweeBirthplace.xml, performerBirthplace.xml.</change>
      </changeLog>
   </history>
</property>

=== uwlib-mig/schemasProject/properties-files/contentNotes.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="https://uwlib-mig.github.io/schemasProject/xsd/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xsi:schemaLocation="https://uwlib-mig.github.io/schemasProject/xsd/
    https://uwlib-mig.github.io/schemasProject/xsd/properties_files.xsd">
    <uid>p99</uid>
    <labels>
        <platformIndependent>contentNotes</platformIndependent>
        <dc>description</dc>
    </labels>
    <uwRequired>
        <uwStandalone>no</uwStandalone>
        <uwObject>no</uwObject>
        <uwItem>no</uwItem>
    </uwRequired>
    <cdm>
        <label>Content Notes</label>
        <cdmDatatype>text</cdmDatatype>
        <cdmLarge>yes</cdmLarge>
        <searchable>yes</searchable>
        <hidden>no</hidden>
        <cdmRequired>no</cdmRequired>
        <cdmControlledVocab>no</cdmControlledVocab>
    </cdm>
    <dspace>
        <dspaceProperty></dspaceProperty>
    </dspace>
    <descriptions>
        <definition><para>A list of the resource's contents.</para></definition>
        <instructions co="no">
            <para>List the contents of the resource.</para>
        </instructions>
        <customization co="no" dd="krab">
            <para>List the contents of the resource.</para>
            <para>Enter each discreet section in a new line.</para>
            <para>When possible, begin the line with temporal starting position of the section.</para>
        </customization>
        <customization co="no" dd="becker" genre_form="Newsletters Records_(Documents)">
            <para>This field may be used to provide a listing of contents; for example a table or contents or a list of headings or sections in a document.</para>
        </customization>
    </descriptions>
    <examples>
        <example co="no">
            <para>example 1:</para>
            <para>00:00:01 Opening music: Alix Dobkin, "Every Woman Can Be a Lesbian" </para>
                <para>00:03:36 Speaker 1: Introduction to the show. First show in this time slot, featuring local lesbian news. Shows will be first Sunday in May. Also Thurs shows at 12-1pm.</para>
                <para>00:04:21  Speaker 2: "Last Sunday you heard the announcement about the split in the radio collective." Lesbian Feminist Radio Collective. Split came about conflicts about content. </para>
            <para>example 2:</para>
            <para>Speaker: Critiques first issue of Dyke Magazine. The Well Dressed Dyke. Article on the Clit Papers (Collective Lesbian International Terrorists). Dykes Behind Bars.  "We at Amazon Media share the costs of purchasing the magazine." Continues to critique second edition. Names various musicians, review of Olivia Records. Mentions Linda Shear, article that she wrote on women’s music. Lesbian Connection magazine. Asked not to air Shear’s new tape or Living with Lesbians. Critiques Out and About newsletter published in Seattle.</para>
        </example>
        <customization co="no" dd="becker" genre_form="Newsletters Records_(Documents)">
            <para>&#x1F6A7;&#x1F6A7;&#x1F6A7;</para>
        </customization>
    </examples>
    <additionalInfo></additionalInfo>
    <marc>
        <dcgMarcMapping></dcgMarcMapping>
    </marc>
    <xsd>
        <typeInfo level="standalone object">
            <typeAttribute>xs:string</typeAttribute>
        </typeInfo>
        <typeInfo level="item">
            <empty/>
        </typeInfo>
    </xsd>
    <rdf></rdf>
    <history>
        <dateCreated>
            <single>2019-08-08</single>
        </dateCreated>
        <created4Coll>KRAB FM Lesbian-Feminist Radio Program Recordings</created4Coll>
        <justification>Special collections wanted a field to insert a list of contents on a soubnd recording of radio broadcasts.</justification>
        <changeLog>
            <change></change>
        </changeLog>
    </history>
</property>

=== uwlib-mig/schemasProject/properties-files/filmmaker.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="https://uwlib-mig.github.io/schemasProject/xsd/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xsi:schemaLocation="https://uwlib-mig.github.io/schemasProject/xsd/
    https://uwlib-mig.github.io/schemasProject/xsd/properties_files.xsd">
    <uid>p102</uid>
    <labels>
        <platformIndependent>filmmaker</platformIndependent>
        <dc>creator</dc>
    </labels>
    <uwRequired>
        <uwStandalone>no</uwStandalone>
        <uwObject>no</uwObject>
        <uwItem>no</uwItem>
    </uwRequired>
    <cdm>
        <label>Filmmaker</label>
        <cdmDatatype>text</cdmDatatype>
        <cdmLarge>no</cdmLarge>
        <searchable>yes</searchable>
        <hidden>no</hidden>
        <cdmRequired>no</cdmRequired>
        <cdmControlledVocab>no</cdmControlledVocab>
    </cdm>
    <dspace>
        <dspaceProperty></dspaceProperty>
    </dspace>
    <descriptions>
        <definition>
            <para>Entity responsible for filming the video.</para>
        </definition>
        <instructions co="no">
            <para>Enter name of person who shot the video.</para>
            <para>Enter the name in inverted form.</para>
        </instructions>
        <instructions co="object">
            <para>Enter name of person who shot the video.</para>
            <para>Enter the name in inverted form.</para>
            <para>Use the form of the name in the LC Name Authority File when possible.</para>
        </instructions>
    </descriptions>
    <examples>
        <example co="no"><para>Hunt, Yvonne (Yvonne M.)</para><para>Karakostas, Christos</para></example>
        <example co="object"><para>Hunt, Yvonne (Yvonne M.)</para><para>Karakostas, Christos</para></example>
    </examples>
    <additionalInfo></additionalInfo>
    <marc>
        <dcgMarcMapping></dcgMarcMapping>
    </marc>
    <xsd>
        <typeInfo level="standalone object">
            <typeAttribute>xs:string</typeAttribute>
        </typeInfo>
    </xsd>
    <rdf>
        <owlDatatypeProperty>yes</owlDatatypeProperty>
    </rdf>
    <history>
        <dateCreated>
            <single>2020-05-18</single>
        </dateCreated>
        <created4Coll>Greek Dances</created4Coll>
        <justification>Needed a field to record the name of the person who recorded the event.</justification>
        <changeLog>
            <change></change>
        </changeLog>
    </history>
</property>
