=== uwlib-mig/schemasProject/xsd/properties_files.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    targetNamespace="https://uwlib-mig.github.io/schemasProject/xsd/"
    xmlns="https://uwlib-mig.github.io/schemasProject/xsd/"
    elementFormDefault="qualified">
    
    <xs:annotation>
        <xs:documentation>2024-04-14</xs:documentation>
        <xs:documentation>properties-files data structures defined here** are currently used in properties-files-to-HTML MAP workflow.</xs:documentation>
        <xs:documentation>**With exceptions such as element 'dspace', 'uwCustom', etc.</xs:documentation>
    </xs:annotation>
    
    <!-- update to include online schemas once stable, use
    https://uwlib-mig.github.io/schemasProject/xsd/genre_form.xsd
    https://uwlib-mig.github.io/schemasProject/xsd/collection.xsd -->
    <xs:include schemaLocation="coll_alias.xsd"/>
    <xs:include schemaLocation="genre_form.xsd"/>
    <xs:include schemaLocation="properties_extensions.xsd"/>
    
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
    <xs:import namespace="http://www.w3.org/2001/XMLSchema"
        schemaLocation="https://www.w3.org/2001/XMLSchema.xsd"/>

    <xs:element name="property" type="propertyType"/> 

    <xs:complexType name="propertyType">
        <xs:sequence>
            <xs:element name="uid">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="p[0-9]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="labels" type="labelType"/>
            <xs:element name="uwRequired" type="uwRequiredType"/>
            <xs:element name="cdm" type="cdmType"/>
            <xs:element name="dspace" type="dspaceType"/>
            <xs:element name="descriptions" type="descriptionsType"/>
            <xs:element name="examples" type="examplesType"/>
            <!-- for below types, see properties_extensions.xsd -->
            <xs:element name="additionalInfo" type="additionalInfoType"/>
            <xs:element name="marc" type="marcType"/>
            <xs:element name="xsd" type="xsdType"/>
            <xs:element name="rdf" type="rdfType"/>
            <xs:element name="history" type="historyType"/>            
        </xs:sequence>
        <xs:attribute ref="xml:base"/>
    </xs:complexType>

    <xs:complexType name="labelType">
        <xs:sequence>
            <xs:element name="platformIndependent" type="xs:string"/>
            <xs:element name="dc" type="dcterms"/>
            <xs:element name="dcNotEng" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="language"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="uwRequiredType">
        <xs:sequence>
            <xs:element name="uwStandalone" type="yesNo"/>
            <xs:element name="uwObject" type="yesNo"/>
            <xs:element name="uwItem" type="yesNo"/>
            <xs:element name="uwCustom" type="uwCustomRequiredType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="uwCustomRequiredType">
        <xs:simpleContent>
            <xs:extension base="yesNo">
                <xs:attribute name="co">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="no"/>
                            <xs:enumeration value="object"/>
                            <xs:enumeration value="item"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="dd" type="dd_type"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="dd_type">
        <xs:restriction>
            <xs:simpleType>
                <xs:list>
                    <xs:simpleType>
                        <xs:restriction base="xs:string"/>
                    </xs:simpleType>
                </xs:list>
            </xs:simpleType>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="cdmType">
        <xs:sequence>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="exportLabel" minOccurs="0" type="xs:string"/>
            <xs:element name="cdmDatatype" type="cdmDatatypeType"/>
            <xs:element name="cdmLarge" type="yesNo"/>
            <xs:element name="searchable" type="yesNo"/>
            <xs:element name="hidden" type="yesNo"/>
            <xs:element name="cdmRequired" type="yesNo"/>
            <xs:element name="cdmControlledVocab" type="yesNo"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="cdmDatatypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="fullText"/>
            <!-- following are not options for CONTENTdm 'Data type' field configuration -->
            <xs:enumeration value="cdmAdministrative"/>
            <xs:enumeration value="uwAdministrative"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="yesNo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
            <xs:enumeration value="notApplicable"/>
            <xs:enumeration value="ifApplicable"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="dspaceType">
        <xs:sequence>
            <xs:element name="dspaceProperty" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="descriptionsType">
        <xs:sequence>
            <xs:element name="definition" type="paraType" maxOccurs="unbounded"/>
            <xs:element name="instructions" type="default_para_type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="customization" type="custom_para_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="paraType">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="examplesType">
        <xs:sequence>
            <xs:element name="example" type="default_para_type" maxOccurs="unbounded"/>
            <xs:element name="customization" type="custom_para_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="dcterms">
        <xs:restriction base="xs:string">
            <xs:enumeration value="none"/>
            <xs:enumeration value="abstract"/>
            <xs:enumeration value="accessRights"/>
            <xs:enumeration value="accrualMethod"/>
            <xs:enumeration value="accrualPeriodicity"/>
            <xs:enumeration value="accrualPolicy"/>
            <xs:enumeration value="alternative"/>
            <xs:enumeration value="audience"/>
            <xs:enumeration value="available"/>
            <xs:enumeration value="bibliographicCitation"/>
            <xs:enumeration value="conformsTo"/>
            <xs:enumeration value="contributor"/>
            <xs:enumeration value="coverage"/>
            <xs:enumeration value="created"/>
            <xs:enumeration value="creator"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="dateAccepted"/>
            <xs:enumeration value="dateCopyrighted"/>
            <xs:enumeration value="dateSubmitted"/>
            <xs:enumeration value="description"/>
            <xs:enumeration value="educationLevel"/>
            <xs:enumeration value="extent"/>
            <xs:enumeration value="format"/>
            <xs:enumeration value="hasFormat"/>
            <xs:enumeration value="hasPart"/>
            <xs:enumeration value="hasVersion"/>
            <xs:enumeration value="identifier"/>
            <xs:enumeration value="instructionalMethod"/>
            <xs:enumeration value="isFormatOf"/>
            <xs:enumeration value="isPartOf"/>
            <xs:enumeration value="isReferencedBy"/>
            <xs:enumeration value="isReplacedBy"/>
            <xs:enumeration value="isRequiredBy"/>
            <xs:enumeration value="issued"/>
            <xs:enumeration value="isVersionOf"/>
            <xs:enumeration value="language"/>
            <xs:enumeration value="license"/>
            <xs:enumeration value="mediator"/>
            <xs:enumeration value="medium"/>
            <xs:enumeration value="modified"/>
            <xs:enumeration value="provenance"/>
            <xs:enumeration value="publisher"/>
            <xs:enumeration value="references"/>
            <xs:enumeration value="relation"/>
            <xs:enumeration value="replaces"/>
            <xs:enumeration value="requires"/>
            <xs:enumeration value="rights"/>
            <xs:enumeration value="rightsHolder"/>
            <xs:enumeration value="source"/>
            <xs:enumeration value="spatial"/>
            <xs:enumeration value="subject"/>
            <xs:enumeration value="tableOfContents"/>
            <xs:enumeration value="temporal"/>
            <xs:enumeration value="title"/>
            <xs:enumeration value="type"/>
            <xs:enumeration value="valid"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="default_para_type">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="co" type="cdm_object_type_type" use="required"/>
    </xs:complexType>

    <xs:complexType name="custom_para_type">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="dd" type="coll_alias_type"/>
        <xs:attribute name="co" type="cdm_object_type_type"/>
        <xs:attribute name="genre_form" type="genre_form_type"/>
    </xs:complexType>
    
    <xs:simpleType name="cdm_object_type_type">
        <xs:annotation>
            <xs:documentation>Use attributes of the type cdm_object_type_type to associate content with a particular kind of CONTENTdm object -- standalone item (sometimes also called standalone object), compound object, or compound-object item (that is, an item which is 'contained' in a compound object.</xs:documentation>
            <xs:documentation>Related: contentdm_maps/xsd/xml_map.xsd - map_structure_cdm_object_type_type</xs:documentation>
            <xs:documentation>Related: contentdm_maps/xsl/functions.xsl - xsl:function cdmm:convert_object_type_notation</xs:documentation>
        </xs:annotation>
        <xs:restriction>
            <xs:simpleType>
                <xs:list>
                    <xs:simpleType>
                        <xs:restriction base="xs:token">
                            <xs:enumeration value="all"/>
                            <xs:enumeration value="no">
                                <xs:annotation>
                                    <xs:documentation>Use this value to indicate that content describes practices for standalone items.</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="object">
                                <xs:annotation>
                                    <xs:documentation>Use this value to indicate that content describes practices for compound objects.</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="item">
                                <xs:annotation>
                                    <xs:documentation>Use this value to indicate that content describes practices for compound-object items.</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <!-- TO DO: eliminate use of 'agnostic', delete enumeration -->
                            <xs:enumeration value="agnostic">
                                <xs:annotation>
                                    <xs:documentation>Meaning/usage of 'agnostic' unclear.</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:list>
            </xs:simpleType>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== uwlib-mig/schemasProject/properties-files/interviewee.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="https://uwlib-mig.github.io/schemasProject/xsd/"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xsi:schemaLocation="https://uwlib-mig.github.io/schemasProject/xsd/
   https://uwlib-mig.github.io/schemasProject/xsd/properties_files.xsd">
   <uid>p45</uid>
   <labels>
      <platformIndependent>interviewee</platformIndependent>
      <dc>creator</dc>
   </labels>
   <uwRequired>
      <uwStandalone>yes</uwStandalone>
      <uwObject>yes</uwObject>
      <uwItem>no</uwItem>
   </uwRequired>
   <cdm>
      <label>Interviewee</label>
      <cdmDatatype>text</cdmDatatype>
      <cdmLarge>no</cdmLarge>
      <searchable>yes</searchable>
      <hidden>no</hidden>
      <cdmRequired>no</cdmRequired>
      <cdmControlledVocab>no</cdmControlledVocab>
   </cdm>
   <dspace>
      <dspaceProperty/>
   </dspace>
   <descriptions>
      <definition>
         <para>A person interviewed.</para>
      </definition>
      <instructions co="no">
         <para>Enter the name of of person interviewed.</para>
         <para>Format of personal name: Lastname, Firstname.</para>
         <para>Use LC Name Authority File for form of name when available: http://authorities.loc.gov or http://id.loc.gov/</para>
         <para>Separate multiple values with a semicolon.</para>
      </instructions>
      <instructions co="object">
         <para>Enter the name of of person interviewed.</para>
         <para>Format of personal name: Lastname, Firstname.</para>
         <para>Use LC Name Authority File for form of name when available: http://authorities.loc.gov or http://id.loc.gov/</para>
         <para>Separate multiple values with a semicolon.</para>
      </instructions>
      <customization co="object" dd="p16786coll3" resourceType="oh">
         <para>Provide the name of the interviewee.</para>
         <para>When appropriate, search the &lt;a href="https://id.loc.gov/authorities/names.html"&gt;Library of Congress Name Authority File&lt;/a&gt; via id.loc.gov for the interviewee name.</para>
         <para>If a potential match is found, confirm that it is the person associated with the resource. It may be helpful to review information included in the web display such as source(s) of information and occupation (for persons), and/or to follow the links provided for exact and/or closely matching concepts from other schemes.</para>
         <para>Copy the name string for use just as it appears at the top of the page, above the URI(s), including dates.</para>
         <para>If no record exists, record personal names as "Lastname, Firstname".</para>
         <para>When recording names without a match in the NAF, reuse the recorded form consistently when the same person or organization appears in the metadata for a different resource.</para>
         <para>For a personal name like Alexander Ben Guiat, "Ben" is considered part of the first name and is transcribed as: "Guiat, Alexander Ben".</para>
         <para>Separate multiple entries with a semicolon and space (“; “).</para>
         <para>Order of values does not matter.</para>
      </customization>
      <customization co="object" dd="temp_alias_001" resourceType="default">
         <para>Enter the name of person(s) interviewed.</para>
         <para>&lt;br/&gt;</para>
         <para>Format personal names as follows:</para>
         <para>[Last Name], [English First Name] [Japanese First Name] [(Maiden name)*]</para>
         <para>*Include a maiden name if provided. Put the maiden name in parentheses.</para>
         <para>Separate multiple values with semicolons.</para>
         <para>&lt;br/&gt;</para>
         <para>UW Libraries cataloging staff: Retain name information entered by project metadata creators; do not replace with LCNAF forms of name.</para>
      </customization>
   </descriptions>
   <examples>
      <example co="object">
         <para>Kinsey, Clark</para>
         <para>Daiber, Ome</para>
         <para>Daiber, Ome; Armstrong, Calvin</para>
         <para>Colbert, Curt, 1947- </para>
         <para>Boeing Company. Boeing Military Aircraft and Missile Systems Group</para>
      </example>
      <example co="all">
         <para>Boyd and Braas</para>
      </example>
      <customization co="no" dd="neareast">
         <para>Noegel, Scott B.</para>
      </customization>
      <customization co="object" dd="uwtoh">
         <para>Honey, Michael K.</para>
         <para>Ellis, Joe, 1947-</para>
      </customization>
      <customization co="object" dd="p16786coll3" resourceType="oh">
         <para>Maimon, Solomon</para>
      </customization>
      <customization co="object" dd="temp_alias_001" resourceType="default">
         <para>Hattori, Fumi (Sato)</para>
         <para>Hayashi, June Mieko (Shirozu)</para>
         <para>Takasugi, Robert Mitsuhiro</para>
      </customization>
   </examples>
   <additionalInfo>
      <admin co="all" dd4para="p16786coll3">
         <para>Default is controlled-vocabulary feature OFF, Sephardic Studies Digital Collection - p16786coll3 requesting ON.</para>
      </admin>
   </additionalInfo>
   <marc>
      <dcgMarcMapping/>
      <marcNotes/>
   </marc>
   <xsd>
      <typeInfo level="standalone object">
         <typeAttribute>xs:string</typeAttribute>
      </typeInfo>
      <typeInfo level="item">
         <empty/>
      </typeInfo>
   </xsd>
   <rdf>
      <sameAs/>
   </rdf>
   <history>
      <dateCreated>
         <range>
            <start>2012-01-01</start>
            <end>2018-03-21</end>
         </range>
      </dateCreated>
      <created4Coll>Special Collections Oral History Collections</created4Coll>
      <justification>Every oral history that involves an interview has an interviewer. Special Collections believed the interview should be described and indexed./</justification>
      <changeLog>
         <change/>
      </changeLog>
   </history>
</property>

=== uwlib-mig/schemasProject/properties-files/digitalFormat.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="https://uwlib-mig.github.io/schemasProject/xsd/"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xsi:schemaLocation="https://uwlib-mig.github.io/schemasProject/xsd/
   https://uwlib-mig.github.io/schemasProject/xsd/properties_files.xsd">
   <uid>p29</uid>
   <labels>
      <platformIndependent>digitalFormat</platformIndependent>
      <dc>format</dc>
   </labels>
   <uwRequired>
      <uwStandalone>no</uwStandalone>
      <uwObject>no</uwObject>
      <uwItem>no</uwItem>
   </uwRequired>
   <cdm>
      <label>Digital Format</label>
      <cdmDatatype>text</cdmDatatype>
      <cdmLarge>no</cdmLarge>
      <searchable>yes</searchable>
      <hidden>no</hidden>
      <cdmRequired>no</cdmRequired>
      <cdmControlledVocab>no</cdmControlledVocab>
   </cdm>
   <dspace>
      <dspaceProperty/>
   </dspace>
   <descriptions>
      <definition>
         <para>File format of a digital resource.</para>
      </definition>
      <instructions co="item">
         <para>Enter the file format of the access item.</para>
         <para>Use media types listed at &lt;a href="http://www.iana.org/assignments/media-types/index.html"&gt;http://www.iana.org/assignments/media-types/index.html&lt;/a&gt;.</para>
         <para>For audio WAVE files, enter "audio/wav".</para>
      </instructions>
      <!-- MIG decision 2020-05: do not include this property in the object description
         <instructions co="object">
         <para>Enter the file formats of the access items.</para>
         <para>Use media types listed at http://www.iana.org/assignments/media-types/index.html</para>
         <para>For audio WAVE files, enter audio/wav.</para>
      </instructions>-->
      <instructions co="no">
         <para>Enter the file format of the access item.</para>
         <para>Use media types listed at &lt;a href="http://www.iana.org/assignments/media-types/index.html"&gt;http://www.iana.org/assignments/media-types/index.html&lt;/a&gt;.</para>
         <para>For audio WAVE files, enter "audio/wav".</para>
      </instructions>
      <customization co="item" dd="p16786coll3" resourceType="oh song text">
         <para>Enter the file format of the file representing the compound-object item--that is, the access item.</para>
         <para>This should be the format of the file given as a value for the digitalFileName property.</para>
         <para>Use media types listed at &lt;a href="http://www.iana.org/assignments/media-types/index.html"&gt;http://www.iana.org/assignments/media-types/index.html&lt;/a&gt;.</para>
         <para>For audio WAVE files, enter "audio/wav".</para>
      </customization>
      <customization co="item" dd="greekdancing" resourceType="default">
         <para>Enter the file format of the compound-object item (video file or table of contents).</para>
         <para>&lt;br/&gt;For .mp4 files enter the following:</para>
         <para>video/mp4</para>
         <para>&lt;br/&gt;For .pdf files enter the following:</para>
         <para>application/pdf</para>
      </customization>
      <customization co="item" dd="temp_alias_001" resourceType="default">
         <para>Enter the file format of the compound-object item.</para>
         <para>This should be the format of the file given as a value for the Original File Name property.</para>
         <para>Use media type values from the &lt;a href="http://www.iana.org/assignments/media-types/index.html"&gt;IANA media types registries&lt;/a&gt;.</para>
         <para>For audio WAVE files, use "audio/wav".</para>
      </customization>
   </descriptions>
   <examples>
      <example co="item">
         <para>audio/mpeg</para>
         <para>image/jpeg</para>
         <para>application/pdf</para>
         <para>text/plain</para>
         <para>video/mp4</para>
      </example>
      <example co="no">
         <para>audio/mpeg</para>
         <para>image/jpeg</para>
         <para>application/pdf</para>
         <para>text/plain</para>
         <para>video/mp4</para>
      </example>
      <customization co="item" dd="greekdancing" resourceType="default">
         <para>video/mp4</para>
         <para>application/pdf</para>
      </customization>
      <!-- MIG decision 2020-05: do not include this property in the object description
      <example co="object">
         <para>video/mp4; application/pdf</para>
      </example>-->
      <customization co="item" dd="temp_alias_001" resourceType="default">
         <para>video/mp4</para>
         <para>audio/mpeg</para>
         <para>audio/wav</para>
         <para>application/pdf</para>
      </customization>
   </examples>
   <additionalInfo/>
   <marc>
      <dcgMarcMapping/>
      <marcNotes>
         <para/>
      </marcNotes>
   </marc>
   <xsd>
      <typeInfo level="item">
         <typeAttribute>xs:string</typeAttribute>
      </typeInfo>
   </xsd>
   <rdf>
      <owlDatatypeProperty>yes</owlDatatypeProperty>
   </rdf>
   <history>
      <dateCreated>
         <single>2012-01-01</single>
      </dateCreated>
      <created4Coll>Special Collections Oral Histories Collections</created4Coll>
      <justification>Special Collections wanted a place to describe the file format of the service copy of the resource..</justification>
      <changeLog>
         <change date="2019-04-22">Added instructions and example for @co="no"</change>
         <change date="2019-05-20">//rdf/owlDatatypeProperty='yes' to push into DCMI 1.1 namespace.</change>
         <change date="2020-06-03">removed object description in accordance with MIG decision.</change>
         <change date="2021-10-23">Encode URL in instructions for output to HTML as a link.</change>
         <change date="2021-10-23">Add custom instructions for SSDC coitems.</change>
         <change date="2022-07-28">Add guidance/examples for Tacoma Japanese Language School Project - temp_alias_001</change>
      </changeLog>
   </history>
</property>
